steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - funcion_cicd
  - --region=us-central1
  - --source=repo-3
  - --trigger-http
  - --runtime=python312
  - --allow-unauthenticated
