#clone repo
steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/hee35/gcp-devops.git']

#docker build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-central1-docker.pkg.dev/${_PROJECT_ID}/cicd-5/${_CINAME}:${_VERSION}','repo-5']

#docker push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us-central1-docker.pkg.dev/${_PROJECT_ID}/cicd-5/${_CINAME}:${_VERSION}']

substitutions:
  _PROJECT_ID: gcp-deops-456000
  _CINAME: gke-image
  _VERSION: v1.0

options:
  logging: CLOUD_LOGGING_ONLY