#clone repo
steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/hee35/gcp-devops.git']

#docker build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-central1-docker.pkg.dev/${_PROJECT_ID}/cicd-5/${_CINAME}:${_VERSION}','repo-5']

#docker push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us-central1-docker.pkg.dev/${_PROJECT_ID}/cicd-5/${_CINAME}:${_VERSION}']

#kubectl set image deployment/cicd-app runimage-sha256-1=us-central1-docker.pkg.dev/${_PROJECT_ID}/cicd-5/${_CINAME}:${_VERSION}
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/cicd-app'
  - 'runimage-sha256-1=us-central1-docker.pkg.dev/${_PROJECT_ID}/cicd-5/${_CINAME}:${_VERSION}'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'

substitutions:
  _PROJECT_ID: gcp-devops-456000
  _CINAME: gke-image
  _VERSION: v2.0

options:
  logging: CLOUD_LOGGING_ONLY